name: CI

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            /Users/runneradmin/AppData/Local/bazelisk
            /Users/runneradmin/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: bazel build --config=ci //...
  test-windows:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            /Users/runneradmin/AppData/Local/bazelisk
            /Users/runneradmin/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: bazel test --config=ci //...
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: bazel build --config=ci //...
  test-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: bazel test --config=ci //...
